"""
Tests for code generators.
"""

import os
import tempfile

import mido
import pytest

from midi2python.generator import generate_exact_code, generate_readable_code
from midi2python.parser import parse_midi_file


def create_test_midi():
    mid = mido.MidiFile(ticks_per_beat=480, type=1)
    track = mido.MidiTrack()
    track.append(mido.MetaMessage("track_name", name="Piano", time=0))
    track.append(mido.MetaMessage("set_tempo", tempo=500000, time=0))
    track.append(mido.MetaMessage("time_signature", numerator=4, denominator=4, time=0))
    track.append(mido.Message("program_change", program=0, channel=0, time=0))
    track.append(mido.Message("note_on", note=60, velocity=64, channel=0, time=0))
    track.append(mido.Message("note_off", note=60, velocity=64, channel=0, time=480))
    track.append(mido.Message("note_on", note=62, velocity=70, channel=0, time=0))
    track.append(mido.Message("note_off", note=62, velocity=70, channel=0, time=480))
    track.append(mido.Message("control_change", control=7, value=100, channel=0, time=0))
    track.append(mido.Message("pitchwheel", pitch=200, channel=0, time=0))
    track.append(mido.MetaMessage("end_of_track", time=0))
    mid.tracks.append(track)
    return mid


def test_generate_exact_code_syntax():
    mid = create_test_midi()
    with tempfile.NamedTemporaryFile(suffix=".mid", delete=False) as f:
        mid.save(f.name)
        midi_path = f.name

    try:
        data = parse_midi_file(midi_path)
        code = generate_exact_code(data, midi_path, "test_output.py", include_comments=True)

        # Check syntax
        compile(code, "<test>", "exec")

        # Check required imports
        assert "from mido import" in code
        assert "MidiFile" in code
        assert "MidiTrack" in code

        # Check constants
        assert "TICKS_PER_BEAT" in code
        assert "OUTPUT_MIDI" in code

        # Check content preservation
        assert "note_on" in code
        assert "note_off" in code
        assert "program_change" in code

    finally:
        os.unlink(midi_path)


def test_generate_exact_code_no_comments():
    mid = create_test_midi()
    with tempfile.NamedTemporaryFile(suffix=".mid", delete=False) as f:
        mid.save(f.name)
        midi_path = f.name

    try:
        data = parse_midi_file(midi_path)
        code = generate_exact_code(data, midi_path, "test_output.py", include_comments=False)
        compile(code, "<test>", "exec")
        # Should still have header but fewer comments
        assert "Generated by MIDI-to-Python" in code
    finally:
        os.unlink(midi_path)


def test_generate_readable_code_syntax():
    mid = create_test_midi()
    with tempfile.NamedTemporaryFile(suffix=".mid", delete=False) as f:
        mid.save(f.name)
        midi_path = f.name

    try:
        data = parse_midi_file(midi_path)
        code = generate_readable_code(data, midi_path, "test_output.py", include_comments=True)
        compile(code, "<test>", "exec")

        # Check readable features
        assert "def note_name" in code
        assert "TICKS_PER_BEAT" in code
        assert "TEMPO" in code or "TEMPO_BPM" in code
        assert "notes_0" in code or "melody" in code

    finally:
        os.unlink(midi_path)


def test_generate_readable_code_no_comments():
    mid = create_test_midi()
    with tempfile.NamedTemporaryFile(suffix=".mid", delete=False) as f:
        mid.save(f.name)
        midi_path = f.name

    try:
        data = parse_midi_file(midi_path)
        code = generate_readable_code(data, midi_path, "test_output.py", include_comments=False)
        compile(code, "<test>", "exec")
    finally:
        os.unlink(midi_path)


def test_generate_exact_code_multiple_tracks():
    mid = mido.MidiFile(ticks_per_beat=480, type=1)
    for i in range(2):
        track = mido.MidiTrack()
        track.append(mido.MetaMessage("track_name", name=f"Track {i}", time=0))
        track.append(mido.Message("note_on", note=60 + i, velocity=64, channel=i, time=0))
        track.append(mido.Message("note_off", note=60 + i, velocity=64, channel=i, time=480))
        mid.tracks.append(track)

    with tempfile.NamedTemporaryFile(suffix=".mid", delete=False) as f:
        mid.save(f.name)
        midi_path = f.name

    try:
        data = parse_midi_file(midi_path)
        code = generate_exact_code(data, midi_path, "test.py")
        compile(code, "<test>", "exec")
        assert "track_0" in code
        assert "track_1" in code
    finally:
        os.unlink(midi_path)


def test_generated_code_contains_header():
    mid = create_test_midi()
    with tempfile.NamedTemporaryFile(suffix=".mid", delete=False) as f:
        mid.save(f.name)
        midi_path = f.name

    try:
        data = parse_midi_file(midi_path)
        for mode_func in [generate_exact_code, generate_readable_code]:
            code = mode_func(data, midi_path, "out.py")
            assert "Generated by MIDI-to-Python" in code
            assert "Source MIDI" in code
    finally:
        os.unlink(midi_path)


def test_chord_detection_in_readable():
    # Create chord: 3 notes at same tick
    mid = mido.MidiFile(ticks_per_beat=480)
    track = mido.MidiTrack()
    track.append(mido.Message("note_on", note=60, velocity=64, channel=0, time=0))
    track.append(mido.Message("note_on", note=64, velocity=64, channel=0, time=0))
    track.append(mido.Message("note_on", note=67, velocity=64, channel=0, time=0))
    track.append(mido.Message("note_off", note=60, velocity=64, channel=0, time=480))
    track.append(mido.Message("note_off", note=64, velocity=64, channel=0, time=0))
    track.append(mido.Message("note_off", note=67, velocity=64, channel=0, time=0))
    mid.tracks.append(track)

    with tempfile.NamedTemporaryFile(suffix=".mid", delete=False) as f:
        mid.save(f.name)
        midi_path = f.name

    try:
        data = parse_midi_file(midi_path)
        code = generate_readable_code(data, midi_path, "out.py")
        # Should detect chord
        assert "CHORDS" in code or "Chord" in code
        compile(code, "<test>", "exec")
    finally:
        os.unlink(midi_path)
