"""
Tests for CLI behavior.
"""

import os
import subprocess
import sys
import tempfile

import mido
import pytest

from midi2python.cli import main, create_parser


def create_simple_midi_file(path):
    mid = mido.MidiFile(ticks_per_beat=480)
    track = mido.MidiTrack()
    track.append(mido.Message("note_on", note=60, velocity=64, time=0))
    track.append(mido.Message("note_off", note=60, velocity=64, time=480))
    mid.tracks.append(track)
    mid.save(path)


def test_cli_parser():
    parser = create_parser()
    args = parser.parse_args(["input.mid"])
    assert args.input == "input.mid"
    assert args.mode == "exact"

    args = parser.parse_args(["input.mid", "-o", "out.py", "--mode", "readable"])
    assert args.output == "out.py"
    assert args.mode == "readable"

    args = parser.parse_args(["input.mid", "--no-comments", "--stdout"])
    assert args.no_comments is True
    assert args.stdout is True


def test_cli_missing_input():
    # No input should return exit code 2
    exit_code = main([])
    assert exit_code == 2


def test_cli_nonexistent_file():
    exit_code = main(["/nonexistent/file.mid"])
    assert exit_code == 1


def test_cli_exact_mode():
    with tempfile.TemporaryDirectory() as tmpdir:
        midi_path = os.path.join(tmpdir, "test.mid")
        py_path = os.path.join(tmpdir, "test.py")
        create_simple_midi_file(midi_path)

        exit_code = main([midi_path, "-o", py_path, "--mode", "exact"])
        assert exit_code == 0
        assert os.path.exists(py_path)

        with open(py_path) as f:
            content = f.read()
        assert "MidiFile" in content
        assert "Generated by MIDI-to-Python" in content


def test_cli_readable_mode():
    with tempfile.TemporaryDirectory() as tmpdir:
        midi_path = os.path.join(tmpdir, "test.mid")
        py_path = os.path.join(tmpdir, "test.py")
        create_simple_midi_file(midi_path)

        exit_code = main([midi_path, "-o", py_path, "--mode", "readable"])
        assert exit_code == 0
        assert os.path.exists(py_path)

        with open(py_path) as f:
            content = f.read()
        assert "def note_name" in content


def test_cli_stdout():
    with tempfile.TemporaryDirectory() as tmpdir:
        midi_path = os.path.join(tmpdir, "test.mid")
        create_simple_midi_file(midi_path)

        # Capture stdout by calling main with --stdout and redirecting?
        # We test via subprocess for more accurate stdout capture
        env = os.environ.copy()
        # Ensure repo root is in PYTHONPATH
        repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
        env["PYTHONPATH"] = repo_root + os.pathsep + env.get("PYTHONPATH", "")
        result = subprocess.run(
            [sys.executable, "-m", "midi2python.cli", midi_path, "--stdout"],
            capture_output=True,
            text=True,
            cwd=tmpdir,
            env=env,
        )
        # Should succeed and output code
        assert result.returncode == 0, f"stdout CLI failed: {result.stderr}"
        assert "MidiFile" in result.stdout


def test_cli_no_comments():
    with tempfile.TemporaryDirectory() as tmpdir:
        midi_path = os.path.join(tmpdir, "test.mid")
        py_path = os.path.join(tmpdir, "test.py")
        create_simple_midi_file(midi_path)

        exit_code = main([midi_path, "-o", py_path, "--no-comments"])
        assert exit_code == 0
        assert os.path.exists(py_path)


def test_cli_invalid_output_path():
    with tempfile.TemporaryDirectory() as tmpdir:
        midi_path = os.path.join(tmpdir, "test.mid")
        create_simple_midi_file(midi_path)

        # Try to write to a directory that doesn't exist and cannot be created? Actually it can be created
        # Instead try invalid path like /proc/invalid
        # Use a path with null byte or unwritable location
        # For simplicity, use a path where parent is a file, not directory
        file_as_dir = os.path.join(tmpdir, "file")
        with open(file_as_dir, "w") as f:
            f.write("x")
        invalid_path = os.path.join(file_as_dir, "output.py")

        exit_code = main([midi_path, "-o", invalid_path])
        assert exit_code == 1


def test_cli_default_output():
    with tempfile.TemporaryDirectory() as tmpdir:
        midi_path = os.path.join(tmpdir, "song.mid")
        create_simple_midi_file(midi_path)

        # Change cwd to tmpdir for default output test
        original_cwd = os.getcwd()
        try:
            os.chdir(tmpdir)
            exit_code = main([midi_path])
            assert exit_code == 0
            # Default output should be song.py in same dir as input
            expected = os.path.join(tmpdir, "song.py")
            assert os.path.exists(expected)
        finally:
            os.chdir(original_cwd)


def test_cli_encoding():
    with tempfile.TemporaryDirectory() as tmpdir:
        midi_path = os.path.join(tmpdir, "test.mid")
        py_path = os.path.join(tmpdir, "test.py")
        create_simple_midi_file(midi_path)

        exit_code = main([midi_path, "-o", py_path, "--encoding", "utf-8"])
        assert exit_code == 0


def test_cli_invalid_encoding():
    with tempfile.TemporaryDirectory() as tmpdir:
        midi_path = os.path.join(tmpdir, "test.mid")
        create_simple_midi_file(midi_path)

        exit_code = main([midi_path, "--encoding", "invalid-encoding-xyz"])
        assert exit_code == 1


def test_cli_help():
    parser = create_parser()
    # Should not raise
    try:
        parser.parse_args(["--help"])
    except SystemExit as e:
        assert e.code == 0


def test_cli_version():
    parser = create_parser()
    try:
        parser.parse_args(["--version"])
    except SystemExit as e:
        assert e.code == 0
