"""
Generated by MIDI-to-Python.

Source MIDI: example.mid
Conversion mode: exact
Ticks per beat: 480
Tracks: 2
Type: 1
"""

from mido import MidiFile, MidiTrack, Message, MetaMessage

# MIDI file configuration

TICKS_PER_BEAT = 480
MIDI_TYPE = 1

OUTPUT_MIDI = "generated_example_recreated.mid"

# Create MIDI file

mid = MidiFile(ticks_per_beat=TICKS_PER_BEAT, type=MIDI_TYPE)

# Track 0: Piano
#   Instruments: Acoustic Grand Piano
#   Channels: [0]
#   Notes: 4
#   Messages: 12

track_0 = MidiTrack()
track_0.append(MetaMessage("track_name", name="Piano", time=0))
track_0.append(MetaMessage("set_tempo", tempo=500000, time=0))
track_0.append(MetaMessage("time_signature", numerator=4, denominator=4, clocks_per_click=24, notated_32nd_notes_per_beat=8, time=0))
track_0.append(MetaMessage("key_signature", key="C", time=0))
track_0.append(Message("program_change", channel=0, program=0, time=0))
track_0.append(Message("note_on", channel=0, note=60, velocity=64, time=0))
track_0.append(Message("note_off", channel=0, note=60, velocity=64, time=480))
track_0.append(Message("note_on", channel=0, note=62, velocity=64, time=0))
track_0.append(Message("note_off", channel=0, note=62, velocity=64, time=480))
track_0.append(Message("note_on", channel=0, note=64, velocity=64, time=0))
track_0.append(Message("note_off", channel=0, note=64, velocity=64, time=480))
track_0.append(MetaMessage("end_of_track", time=0))
mid.tracks.append(track_0)

# Track 1: Bass
#   Instruments: Acoustic Bass
#   Channels: [1]
#   Notes: 2
#   Messages: 6

track_1 = MidiTrack()
track_1.append(MetaMessage("track_name", name="Bass", time=0))
track_1.append(Message("program_change", channel=1, program=32, time=0))
track_1.append(Message("note_on", channel=1, note=36, velocity=80, time=0))
track_1.append(Message("note_off", channel=1, note=36, velocity=80, time=960))
track_1.append(Message("note_on", channel=1, note=38, velocity=80, time=0))
track_1.append(Message("note_off", channel=1, note=38, velocity=80, time=960))
track_1.append(MetaMessage("end_of_track", time=0))
mid.tracks.append(track_1)

# Save the recreated MIDI file
mid.save(OUTPUT_MIDI)

print(f"Recreated MIDI saved to {OUTPUT_MIDI}")
print(f"Tracks: {len(mid.tracks)}")
print(f"Ticks per beat: {mid.ticks_per_beat}")
print(f"Type: {mid.type}")


def get_midi():
    """Return the recreated MidiFile object."""
    return mid

if __name__ == "__main__":
    # Already saved above, just confirm
    pass
