"""
Code generators for MIDI-to-Python conversion.

Two modes:
- exact: Preserve MIDI data as accurately as possible
- readable: Generate human-readable musical structures
"""

from __future__ import annotations

import os
import textwrap
from typing import List

from .models import MidiFileData
from .utils import (
    get_program_name,
    midi_note_to_name,
    sanitize_filename,
    tempo_to_bpm,
    ticks_to_beats,
)


def _escape_string(s: str) -> str:
    """Escape string for Python repr, handling special cases."""
    return repr(s)


def _message_to_code(msg, use_repr: bool = True) -> str:
    """
    Convert a ParsedMessage to Python code string.

    Returns code like: Message('note_on', channel=0, note=60, velocity=64, time=0)
    or MetaMessage('set_tempo', tempo=500000, time=0)
    """
    # Build args
    args_parts = []
    # Determine if meta
    # Use data dict
    data = msg.data.copy()
    channel = msg.channel

    # For reconstruction, we need to include channel if present and not in data
    if channel is not None and "channel" not in data and not msg.is_meta:
        # Insert channel first for readability
        args_parts.append(f"channel={channel}")

    # Add other data
    for key, value in sorted(data.items()):
        if key == "channel" and channel is not None:
            # Already handled, but ensure we output channel
            if f"channel={channel}" not in args_parts:
                args_parts.append(f"channel={value}")
            else:
                # If channel already added, skip duplicate but ensure correct value
                continue
            continue

        # Handle bytes data (e.g., sysex)
        if isinstance(value, (bytes, bytearray)):
            args_parts.append(f"{key}={list(value)}")
        elif isinstance(value, str):
            args_parts.append(f"{key}={_escape_string(value)}")
        else:
            args_parts.append(f"{key}={repr(value)}")

    # Add time last
    args_parts.append(f"time={msg.time}")

    args_str = ", ".join(args_parts)
    if msg.is_meta:
        return f'MetaMessage("{msg.type}", {args_str})' if args_str else f'MetaMessage("{msg.type}")'
    else:
        return f'Message("{msg.type}", {args_str})' if args_str else f'Message("{msg.type}")'


def _generate_header(
    source_midi: str, mode: str, midi_data: MidiFileData, include_comments: bool = True
) -> str:
    """Generate file header."""
    source_basename = os.path.basename(source_midi)
    header = f'"""\nGenerated by MIDI-to-Python.\n\nSource MIDI: {source_basename}\nConversion mode: {mode}\nTicks per beat: {midi_data.ticks_per_beat}\nTracks: {midi_data.track_count}\nType: {midi_data.type}\n"""\n\n'
    header += "from mido import MidiFile, MidiTrack, Message, MetaMessage\n\n"
    return header


def generate_exact_code(
    midi_data: MidiFileData,
    source_path: str,
    output_py_path: str,
    include_comments: bool = True,
) -> str:
    """
    Generate exact mode Python code.

    Preserves all MIDI data as accurately as possible.
    """
    lines: List[str] = []

    # Header
    lines.append(_generate_header(source_path, "exact", midi_data, include_comments))

    # Constants
    if include_comments:
        lines.append("# MIDI file configuration\n")
    lines.append(f"TICKS_PER_BEAT = {midi_data.ticks_per_beat}")
    lines.append(f"MIDI_TYPE = {midi_data.type}\n")

    # Output file name
    output_base = os.path.splitext(os.path.basename(output_py_path))[0]
    recreated_name = sanitize_filename(f"{output_base}_recreated.mid")
    lines.append(f'OUTPUT_MIDI = "{recreated_name}"\n')

    if include_comments:
        lines.append("# Create MIDI file\n")
    lines.append("mid = MidiFile(ticks_per_beat=TICKS_PER_BEAT, type=MIDI_TYPE)\n")

    # Generate tracks
    for track_idx, track in enumerate(midi_data.tracks):
        if include_comments:
            lines.append(f"# Track {track_idx}: {track.name}")
            if track.program_numbers:
                prog_names = [get_program_name(p) for p in track.program_numbers]
                lines.append(f"#   Instruments: {', '.join(prog_names)}")
            if track.channels:
                lines.append(f"#   Channels: {track.channels}")
            lines.append(f"#   Notes: {len(track.notes)}")
            lines.append(f"#   Messages: {len(track.messages)}\n")

        lines.append(f"track_{track_idx} = MidiTrack()")
        # Optional: set name attribute for debugging (not standard, but we use append)
        # Actually track name is stored as meta message, so we just recreate messages

        for msg in track.messages:
            code = _message_to_code(msg)
            lines.append(f"track_{track_idx}.append({code})")

        lines.append(f"mid.tracks.append(track_{track_idx})\n")

    # Save
    lines.append("# Save the recreated MIDI file")
    lines.append(f'mid.save(OUTPUT_MIDI)\n')
    lines.append(f'print(f"Recreated MIDI saved to {{OUTPUT_MIDI}}")')
    lines.append(f'print(f"Tracks: {{len(mid.tracks)}}")')
    lines.append(f'print(f"Ticks per beat: {{mid.ticks_per_beat}}")')
    lines.append(f'print(f"Type: {{mid.type}}")\n')

    # Add main guard for good practice, but keep executable at import
    # The spec says running python song.py should generate song_recreated.mid
    # So we keep save at top level, but also add function
    full_code = "\n".join(lines)

    # Wrap in a main function for reusability, but keep top-level execution
    # Actually we already have top-level save, so just add helper
    extra = textwrap.dedent(
        """
        def get_midi():
            \"\"\"Return the recreated MidiFile object.\"\"\"
            return mid

        if __name__ == "__main__":
            # Already saved above, just confirm
            pass
        """
    )
    full_code += "\n" + extra

    return full_code


def generate_readable_code(
    midi_data: MidiFileData,
    source_path: str,
    output_py_path: str,
    include_comments: bool = True,
) -> str:
    """
    Generate readable mode Python code.

    Attempts to make musical information understandable while preserving correctness.
    """
    lines: List[str] = []

    # Header
    lines.append(_generate_header(source_path, "readable", midi_data, include_comments))

    # Imports and helpers
    lines.append("from mido import MidiFile, MidiTrack, Message, MetaMessage\n")

    # Helper functions
    helpers = textwrap.dedent(
        '''
        # Helper functions for readable musical representation

        NOTE_NAMES = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"]

        def note_name(midi_note: int) -> str:
            """Convert MIDI note number to note name (e.g., 60 -> C4)."""
            if not 0 <= midi_note <= 127:
                return f"Note{midi_note}"
            octave = (midi_note // 12) - 1
            name = NOTE_NAMES[midi_note % 12]
            return f"{name}{octave}"

        def note_number(name: str) -> int:
            """Convert note name like C4 to MIDI number."""
            import re
            m = re.match(r"^([A-Ga-g])(#?)(-?\\d+)$", name.strip())
            if not m:
                raise ValueError(f"Invalid note name: {name}")
            letter = m.group(1).upper()
            sharp = m.group(2)
            octave = int(m.group(3))
            base = {"C": 0, "D": 2, "E": 4, "F": 5, "G": 7, "A": 9, "B": 11}[letter]
            if sharp:
                base += 1
            return (octave + 1) * 12 + base

        def ticks_to_beats(ticks: int, ticks_per_beat: int) -> float:
            return ticks / ticks_per_beat if ticks_per_beat else 0.0

        def beats_to_ticks(beats: float, ticks_per_beat: int) -> int:
            return int(round(beats * ticks_per_beat))

        def add_note(track, note, start_tick, duration_ticks, velocity=64, channel=0, last_tick_ref=None):
            """
            Helper to add a note to a track using absolute timing.
            Returns new absolute tick position.
            """
            # This helper is for readability; actual implementation below uses delta times
            # For simplicity in generated code, we manage delta times manually
            return start_tick + duration_ticks

        def add_chord(track, notes, start_tick, duration_ticks, velocity=64, channel=0):
            """Helper to add a chord (multiple notes at same time)."""
            for n in notes:
                track.append(Message('note_on', channel=channel, note=n, velocity=velocity, time=0))
            # Note: This is simplified; full implementation manages timing
            return start_tick + duration_ticks

        '''
    )
    lines.append(helpers)

    # Constants
    if include_comments:
        lines.append("# MIDI Configuration\n")
    lines.append(f"TICKS_PER_BEAT = {midi_data.ticks_per_beat}")
    lines.append(f"MIDI_TYPE = {midi_data.type}")

    # Tempo
    if midi_data.tempo_changes:
        first_tempo = midi_data.tempo_changes[0][1]
        bpm = tempo_to_bpm(first_tempo)
        lines.append(f"TEMPO = {first_tempo}  # microseconds per beat, {bpm:.2f} BPM")
        lines.append(f"TEMPO_BPM = {bpm:.2f}")
    else:
        lines.append("TEMPO = 500000  # default 120 BPM")
        lines.append("TEMPO_BPM = 120.0")

    # Time signature
    if midi_data.time_signatures:
        _, (num, den, clocks, notated) = midi_data.time_signatures[0]
        lines.append(f"TIME_SIGNATURE = ({num}, {den})  # {num}/{den}")
        lines.append(f"TIME_SIGNATURE_DETAILS = ({num}, {den}, {clocks}, {notated})")
    else:
        lines.append("TIME_SIGNATURE = (4, 4)")

    # Key signature
    if midi_data.key_signatures:
        _, key = midi_data.key_signatures[0]
        lines.append(f'KEY_SIGNATURE = "{key}"')
    else:
        lines.append('KEY_SIGNATURE = "C"  # default')

    lines.append("")

    output_base = os.path.splitext(os.path.basename(output_py_path))[0]
    recreated_name = sanitize_filename(f"{output_base}_recreated.mid")
    lines.append(f'OUTPUT_MIDI = "{recreated_name}"\n')

    # Global musical analysis
    if include_comments:
        lines.append("# Musical Analysis")
        lines.append(f"# Total tracks: {midi_data.track_count}")
        lines.append(f"# Total ticks: {midi_data.total_ticks}")
        if midi_data.first_tempo_bpm:
            lines.append(f"# Tempo: {midi_data.first_tempo_bpm:.2f} BPM")
        if midi_data.first_time_signature:
            ts = midi_data.first_time_signature
            lines.append(f"# Time Signature: {ts[0]}/{ts[1]}")
        if midi_data.first_key_signature:
            lines.append(f"# Key Signature: {midi_data.first_key_signature}")
        lines.append("")

    # Create MIDI file
    lines.append("mid = MidiFile(ticks_per_beat=TICKS_PER_BEAT, type=MIDI_TYPE)\n")

    # Per-track generation with readable structures
    for track_idx, track in enumerate(midi_data.tracks):
        if include_comments:
            lines.append(f"# {'='*60}")
            lines.append(f"# Track {track_idx}: {track.name}")
            lines.append(f"# {'='*60}")
            if track.program_numbers:
                for prog in track.program_numbers:
                    lines.append(f"# Instrument: {get_program_name(prog)} (program {prog})")
            if track.channels:
                lines.append(f"# Channels: {track.channels}")
            if track.is_drum:
                lines.append(f"# Drum track")
            lines.append(f"# Notes: {len(track.notes)}")
            lines.append(f"# Messages: {len(track.messages)}")
            if track.notes:
                # Show some note range
                notes_sorted = sorted(track.notes, key=lambda n: n.note)
                low = midi_note_to_name(notes_sorted[0].note)
                high = midi_note_to_name(notes_sorted[-1].note)
                lines.append(f"# Note range: {low} ({notes_sorted[0].note}) to {high} ({notes_sorted[-1].note})")
            lines.append("")

        # Track creation
        lines.append(f"track_{track_idx} = MidiTrack()  # {track.name}")

        # Generate readable note representation if notes exist
        if track.notes:
            # Group notes by start time to detect chords
            from collections import defaultdict

            grouped = defaultdict(list)
            for n in track.notes:
                grouped[n.start_tick].append(n)

            # Create a readable melody structure
            lines.append(f"\n# Musical notes for track {track_idx}: {track.name}")
            lines.append(f"# Format: (note_name, midi_number, start_beats, duration_beats, velocity, channel)")

            # For readability, limit to first 100 notes in comment? No, include all in data structure
            lines.append(f"notes_{track_idx} = [")
            for note in track.notes[:200]:  # limit display for huge files but still accurate
                name = midi_note_to_name(note.note)
                start_beats = ticks_to_beats(note.start_tick, midi_data.ticks_per_beat)
                dur_beats = ticks_to_beats(note.duration_ticks, midi_data.ticks_per_beat)
                lines.append(
                    f'    ("{name}", {note.note}, {start_beats:.3f}, {dur_beats:.3f}, {note.velocity}, {note.channel}),  # tick {note.start_tick}'
                )
            if len(track.notes) > 200:
                lines.append(f"    # ... and {len(track.notes) - 200} more notes")
            lines.append("]\n")

            # Detect chords
            chords = [(tick, ns) for tick, ns in grouped.items() if len(ns) > 1]
            if chords:
                lines.append(f"# Detected {len(chords)} chords in this track")
                lines.append(f"CHORDS_{track_idx} = {{")
                # Show up to 20 chords for readability
                for tick, chord_notes in sorted(chords)[:20]:
                    chord_notes_sorted = sorted(chord_notes, key=lambda n: n.note)
                    note_names = [midi_note_to_name(n.note) for n in chord_notes_sorted]
                    midi_numbers = [n.note for n in chord_notes_sorted]
                    beats = ticks_to_beats(tick, midi_data.ticks_per_beat)
                    lines.append(
                        f'    "Chord_at_{beats:.2f}beats": {{"notes": {midi_numbers}, "names": {note_names}, "tick": {tick}}},'
                    )
                if len(chords) > 20:
                    lines.append(f"    # ... and {len(chords) - 20} more chords")
                lines.append("}\n")

            # Melody as simple sequence (note, duration) for monophonic parts
            # Only if track is mostly monophonic
            if len(chords) < len(track.notes) * 0.3:  # mostly monophonic
                lines.append(f"# Simple melody representation (note, duration_beats)")
                lines.append(f"melody_{track_idx} = [")
                for note in track.notes[:100]:
                    name = midi_note_to_name(note.note)
                    dur_beats = ticks_to_beats(note.duration_ticks, midi_data.ticks_per_beat)
                    lines.append(f'    ("{name}", {dur_beats:.3f}),')
                if len(track.notes) > 100:
                    lines.append(f"    # ... and {len(track.notes) - 100} more")
                lines.append("]\n")

        # Now generate actual MIDI messages preserving timing
        # We need to handle delta times correctly - use absolute tick tracking
        if include_comments:
            lines.append(f"# Reconstruct track {track_idx} with accurate timing")

        # For readable mode, we still need to output all messages, but we can add comments for musical events
        # We'll output messages with comments where possible

        # Track absolute tick for comment generation
        abs_tick = 0
        for msg in track.messages:
            abs_tick = msg.abs_tick
            beats = ticks_to_beats(abs_tick, midi_data.ticks_per_beat)

            # Add comment for note events
            comment = ""
            if include_comments:
                if msg.type in ("note_on", "note_off"):
                    note_num = msg.data.get("note")
                    if note_num is not None:
                        comment = f"  # {midi_note_to_name(note_num)} at {beats:.2f} beats (tick {abs_tick})"
                elif msg.type == "program_change":
                    prog = msg.data.get("program", 0)
                    comment = f"  # {get_program_name(prog)}"
                elif msg.type == "set_tempo":
                    tempo = msg.data.get("tempo", 500000)
                    bpm = tempo_to_bpm(tempo)
                    comment = f"  # {bpm:.2f} BPM"
                elif msg.type == "time_signature":
                    num = msg.data.get("numerator", 4)
                    den = msg.data.get("denominator", 4)
                    comment = f"  # Time sig: {num}/{den}"
                elif msg.type == "key_signature":
                    key = msg.data.get("key", "C")
                    comment = f"  # Key: {key}"
                elif msg.type == "control_change":
                    cc = msg.data.get("control", 0)
                    val = msg.data.get("value", 0)
                    comment = f"  # CC {cc} = {val}"

            code = _message_to_code(msg)
            lines.append(f"track_{track_idx}.append({code}){comment}")

        lines.append(f"mid.tracks.append(track_{track_idx})\n")

    # Save
    lines.append("# Save the recreated MIDI file")
    lines.append("mid.save(OUTPUT_MIDI)")
    lines.append('print(f"Recreated MIDI saved to {OUTPUT_MIDI}")')
    lines.append("print(f\"Tracks: {len(mid.tracks)}\")")
    lines.append("print(f\"Ticks per beat: {mid.ticks_per_beat}\")")
    lines.append('print(f"Tempo: {TEMPO_BPM} BPM")')
    lines.append('print(f"Time Signature: {TIME_SIGNATURE}")')
    lines.append('print(f"Key Signature: {KEY_SIGNATURE}")\n')

    # Add helper functions for user
    extra = textwrap.dedent(
        '''
        def get_midi():
            """Return the recreated MidiFile object."""
            return mid

        def get_notes(track_index=0):
            """Get notes for a specific track."""
            var_name = f"notes_{track_index}"
            return globals().get(var_name, [])

        def get_chords(track_index=0):
            """Get chords for a specific track."""
            var_name = f"CHORDS_{track_index}"
            return globals().get(var_name, {})

        if __name__ == "__main__":
            print("\\nMusical Summary:")
            for i, track in enumerate(mid.tracks):
                print(f"  Track {i}: {len(track)} messages")
        '''
    )
    lines.append(extra)

    return "\n".join(lines)
